- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: gravio
  currency: gio
  min_confirm: 1
  max_confirm: 6
- id: 600
  key: doge
  currency: doge
  min_confirm: 1
  max_confirm: 6
- id: 800
  key: ltc
  currency: ltc
  min_confirm: 1
  max_confirm: 6
- id: 1000
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6

