- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 2
  max_confirm: 3
- id: 400
  key: gravio
  currency: gio
  min_confirm: 5
  max_confirm: 6
- id: 600
  key: doge
  currency: doge
  min_confirm: 5
  max_confirm: 6
- id: 800
  key: ltc
  currency: ltc
  min_confirm: 5
  max_confirm: 6
- id: 1000
  key: ether
  currency: eth
  min_confirm: 5
  max_confirm: 6
- id: 2000
  key: touristcoin
  currency: tou
  min_confirm: 5
  max_confirm: 6
# - id: 1200
#   key: poseidon
#   currency: psd
#   min_confirm: 4
#   max_confirm: 5
# - id: 1400
#   key: profithunter
#   currency: phc
#   min_confirm: 5
#   max_confirm: 6
# - id: 1600
#   key: xgoldcoin
#   currency: xgc
#   min_confirm: 3
#   max_confirm: 4
# - id: 1800
#   key: deviant
#   currency: dev
#   min_confirm: 5
#   max_confirm: 6
# - id: 2000
#   key: phoboscoin
#   currency: pbs
#   min_confirm: 4
#   max_confirm: 5
# - id: 2200
#   key: dinero
#   currency: din
#   min_confirm: 5
#   max_confirm: 6
# - id: 2400
#   key: advance
#   currency: adv
#   min_confirm: 5
#   max_confirm: 6
# - id: 2600
#   key: dv7coin
#   currency: dv7
#   min_confirm: 5
#   max_confirm: 6
# - id: 2800
#   key: shekel
#   currency: jew
#   min_confirm: 5
#   max_confirm: 6
# - id: 3000
#   key: argo
#   currency: argo
#   min_confirm: 5
#   max_confirm: 6
# - id: 3200
#   key: escrow
#   currency: esco
#   min_confirm: 5
#   max_confirm: 6
# - id: 3400
#   key: neetcoin
#   currency: neet
#   min_confirm: 5
#   max_confirm: 6
# - id: 3600
#   key: xylo
#   currency: xylo
#   min_confirm: 5
#   max_confirm: 6
# - id: 3800
#   key: steepcoin
#   currency: steep
#   min_confirm: 5
#   max_confirm: 6
# - id: 4000
#   key: bitcoingreen
#   currency: bitg
#   min_confirm: 5
#   max_confirm: 6
# - id: 4200
#   key: craftr
#   currency: crft
#   min_confirm: 5
#   max_confirm: 6
# - id: 4400
#   key: enviromint
#   currency: env
#   min_confirm: 5
#   max_confirm: 6
# - id: 4600
#   key: snowgem
#   currency: xsg
#   min_confirm: 5
#   max_confirm: 6
# - id: 4800
#   key: newyorkcoin
#   currency: nyc
#   min_confirm: 2
#   max_confirm: 3
# - id: 5000
#   key: zeroonecoin
#   currency: zoc
#   min_confirm: 5
#   max_confirm: 6
# - id: 5200
#   key: bitcoinz
#   currency: btcz
#   min_confirm: 5
#   max_confirm: 6
# - id: 5400
#   key: yenten
#   currency: ytn
#   min_confirm: 5
#   max_confirm: 6
# - id: 5600
#   key: yicoin
#   currency: yic
#   min_confirm: 5
#   max_confirm: 6
# - id: 5800
#   key: tulipcoin
#   currency: tlp
#   min_confirm: 5
#   max_confirm: 6
# - id: 6000
#   key: pawcoin
#   currency: pwc
#   min_confirm: 5
#   max_confirm: 6
# - id: 6200
#   key: stronghand
#   currency: shnd
#   min_confirm: 5
#   max_confirm: 6
# - id: 6400
#   key: lemanum
#   currency: lmn
#   min_confirm: 5
#   max_confirm: 6
# - id: 6600
#   key: keyco
#   currency: kec
#   min_confirm: 5
#   max_confirm: 6
# - id: 6800
#   key: absolute
#   currency: abs
#   min_confirm: 5
#   max_confirm: 6
# - id: 7000
#   key: suppocoin
#   currency: suppo
#   min_confirm: 5
#   max_confirm: 6
# - id: 7200
#   key: linda
#   currency: linda
#   min_confirm: 5
#   max_confirm: 6
# - id: 7400
#   key: highcoin
#   currency: hight
#   min_confirm: 5
#   max_confirm: 6
# - id: 7600
#   key: blisscoin
#   currency: bls
#   min_confirm: 5
#   max_confirm: 6
# - id: 7800
#   key: tokyo
#   currency: tokc
#   min_confirm: 5
#   max_confirm: 6
# - id: 8000
#   key: elleriumcoin
#   currency: elp
#   min_confirm: 5
#   max_confirm: 6
# - id: 8200
#   key: zexcoin
#   currency: zex
#   min_confirm: 5
#   max_confirm: 6
# - id: 8400
#   key: rulitecoin
#   currency: rlc
#   min_confirm: 5
#   max_confirm: 6
# - id: 8600
#   key: luckybit
#   currency: lucky
#   min_confirm: 5
#   max_confirm: 6
# - id: 8800
#   key: instacashcoin
#   currency: ich
#   min_confirm: 5
#   max_confirm: 6
# - id: 9000
#   key: mambocoin
#   currency: mmb
#   min_confirm: 5
#   max_confirm: 6
# - id: 9200
#   key: phantomxcoin
#   currency: pnx
#   min_confirm: 5
#   max_confirm: 6
# - id: 9400
#   key: mixcoin
#   currency: mix
#   min_confirm: 110
#   max_confirm: 120
# - id: 9600
#   key: kredscoin
#   currency: kreds
#   min_confirm: 5
#   max_confirm: 6
# - id: 9800
#   key: bankittcoin
#   currency: bkt
#   min_confirm: 5
#   max_confirm: 6
# - id: 10000
#   key: snxcoin
#   currency: snx
#   min_confirm: 5
#   max_confirm: 6
# - id: 10200
#   key: girocoin
#   currency: giro
#   min_confirm: 5
#   max_confirm: 6
# - id: 10400
#   key: onexcoin
#   currency: onex
#   min_confirm: 5
#   max_confirm: 6
# - id: 10600
#   key: pushicoin
#   currency: pushi
#   min_confirm: 5
#   max_confirm: 6
# - id: 10800
#   key: virtuscoin
#   currency: vrt
#   min_confirm: 5
#   max_confirm: 6
# - id: 11000
#   key: zacacoin
#   currency: zaca
#   min_confirm: 5
#   max_confirm: 6
# - id: 11200
#   key: xhimeracoin
#   currency: xhm
#   min_confirm: 5
#   max_confirm: 6
# - id: 11400
#   key: xarucoin
#   currency: xar
#   min_confirm: 5
#   max_confirm: 6
# - id: 11600
#   key: rupayacoin
#   currency: rupx
#   min_confirm: 5
#   max_confirm: 6
# - id: 11800
#   key: ferrumcoin
#   currency: frm
#   min_confirm: 5
#   max_confirm: 6
# - id: 12000
#   key: peoplecoin
#   currency: men
#   min_confirm: 5
#   max_confirm: 6
# - id: 12200
#   key: muncoin
#   currency: mun
#   min_confirm: 5
#   max_confirm: 6
# - id: 12400
#   key: millioncoin
#   currency: onemc
#   min_confirm: 5
#   max_confirm: 6
# - id: 12600
#   key: alphacoin
#   currency: alp
#   min_confirm: 5
#   max_confirm: 6
# - id: 12800
#   key: zelcashcoin
#   currency: zel
#   min_confirm: 5
#   max_confirm: 6
# - id: 13000
#   key: amerocoin
#   currency: amx
#   min_confirm: 5
#   max_confirm: 6
# - id: 13200
#   key: brofistcoin
#   currency: pew
#   min_confirm: 5
#   max_confirm: 6
# - id: 13400
#   key: friendshipcoin
#   currency: fsc
#   min_confirm: 5
#   max_confirm: 6
# - id: 13600
#   key: salencoin
#   currency: sln
#   min_confirm: 5
#   max_confirm: 6
# - id: 13800
#   key: unifiedsocietycoin
#   currency: usx
#   min_confirm: 5
#   max_confirm: 6
# - id: 14000
#   key: bitspacecoin
#   currency: bsx
#   min_confirm: 5
#   max_confirm: 6
# - id: 14200
#   key: eotcoin
#   currency: eot
#   min_confirm: 5
#   max_confirm: 6
# - id: 14400
#   key: apolloncoin
#   currency: xap
#   min_confirm: 5
#   max_confirm: 6
# - id: 14600
#   key: miacoin
#   currency: miac
#   min_confirm: 5
#   max_confirm: 6
# - id: 14800
#   key: krakencoin
#   currency: kc
#   min_confirm: 5
#   max_confirm: 6
# - id: 15000
#   key: archimedcoin
#   currency: arhm
#   min_confirm: 5
#   max_confirm: 6
# - id: 15200
#   key: olympiccoin
#   currency: olmp
#   min_confirm: 5
#   max_confirm: 6
# - id: 15400
#   key: onzcoin
#   currency: onz
#   min_confirm: 5
#   max_confirm: 6
# - id: 15600
#   key: agenacoin
#   currency: agn
#   min_confirm: 5
#   max_confirm: 6
# - id: 15800
#   key: corezcoin
#   currency: crz
#   min_confirm: 5
#   max_confirm: 6
# - id: 16000
#   key: enixtcoin
#   currency: enix
#   min_confirm: 5
#   max_confirm: 6
# - id: 16200
#   key: stannumcoin
#   currency: snc
#   min_confirm: 5
#   max_confirm: 6
# - id: 16400
#   key: quazcoin
#   currency: quaz
#   min_confirm: 5
#   max_confirm: 6
# - id: 16600
#   key: scrivcoin
#   currency: scriv
#   min_confirm: 5
#   max_confirm: 6
# - id: 16800
#   key: ethfcoin
#   currency: ethf
#   min_confirm: 5
#   max_confirm: 6
# - id: 17000
#   key: arepacoin
#   currency: arepa
#   min_confirm: 5
#   max_confirm: 6
# - id: 17200
#   key: sub1xcoin
#   currency: sub1x
#   min_confirm: 5
#   max_confirm: 6
# - id: 17400
#   key: cheesecoin
#   currency: cheese
#   min_confirm: 5
#   max_confirm: 6
# - id: 17600
#   key: jiyocoin
#   currency: jiyo
#   min_confirm: 5
#   max_confirm: 6
# - id: 17800
#   key: pyrocoin
#   currency: pyro
#   min_confirm: 5
#   max_confirm: 6
# - id: 18000
#   key: rovercoin
#   currency: roe
#   min_confirm: 5
#   max_confirm: 6
# - id: 18200
#   key: citruscoin
#   currency: citr
#   min_confirm: 5
#   max_confirm: 6
# - id: 18400
#   key: xeoncoin
#   currency: xen
#   min_confirm: 5
#   max_confirm: 6
# - id: 18600
#   key: edollarcoin
#   currency: edl
#   min_confirm: 10
#   max_confirm: 11
# - id: 18800
#   key: curiumcoin
#   currency: cru
#   min_confirm: 5
#   max_confirm: 6
# - id: 19000
#   key: needlecoin
#   currency: ndc
#   min_confirm: 5
#   max_confirm: 6
# - id: 19200
#   key: zaliascoin
#   currency: zls
#   min_confirm: 5
#   max_confirm: 6
# - id: 19400
#   key: protoncoin
#   currency: proton
#   min_confirm: 5
#   max_confirm: 6
# - id: 19600
#   key: kraitcoin
#   currency: krait
#   min_confirm: 5
#   max_confirm: 6
# - id: 19800
#   key: alphanodecoin
#   currency: aln
#   min_confirm: 5
#   max_confirm: 6
# - id: 20000
#   key: bcpcoin
#   currency: bcp
#   min_confirm: 2
#   max_confirm: 3
# - id: 20200
#   key: xumacoin
#   currency: xmx
#   min_confirm: 5
#   max_confirm: 6
# - id: 20400
#   key: idapaycoin
#   currency: ida
#   min_confirm: 5
#   max_confirm: 6
# - id: 20600
#   key: unifycoin
#   currency: unify
#   min_confirm: 5
#   max_confirm: 6
# - id: 20800
#   key: andcoin
#   currency: and
#   min_confirm: 5
#   max_confirm: 6
# - id: 21000
#   key: thevigcoin
#   currency: vig
#   min_confirm: 5
#   max_confirm: 6
# - id: 21200
#   key: pepegoldcoin
#   currency: peps
#   min_confirm: 5
#   max_confirm: 6
# - id: 21400
#   key: vizzotopcoin
#   currency: vizz
#   min_confirm: 5
#   max_confirm: 6
# - id: 21600
#   key: monsterbitcoin
#   currency: mon
#   min_confirm: 5
#   max_confirm: 6
# - id: 21800
#   key: lunexcoin
#   currency: lunex
#   min_confirm: 5
#   max_confirm: 6
# - id: 22000
#   key: prufuscoin
#   currency: pruf
#   min_confirm: 5
#   max_confirm: 6
# - id: 22200
#   key: wantcoin
#   currency: want
#   min_confirm: 5
#   max_confirm: 6
# - id: 22400
#   key: mmocoin
#   currency: mmo
#   min_confirm: 5
#   max_confirm: 6
# - id: 22600
#   key: carebitcoin
#   currency: cbt
#   min_confirm: 5
#   max_confirm: 6
# - id: 22800
#   key: xt3chcoin
#   currency: xt3
#   min_confirm: 5
#   max_confirm: 6
# - id: 23000
#   key: btcfcoin
#   currency: btcf
#   min_confirm: 5
#   max_confirm: 6
# - id: 23200
#   key: zcorecoin
#   currency: zcr
#   min_confirm: 5
#   max_confirm: 6
# - id: 23400
#   key: solariumcoin
#   currency: slrc
#   min_confirm: 5
#   max_confirm: 6
# - id: 23600
#   key: aevocoin
#   currency: aevo
#   min_confirm: 5
#   max_confirm: 6
# - id: 23800
#   key: platopaycoin
#   currency: ppx
#   min_confirm: 5
#   max_confirm: 6
# - id: 24000
#   key: yobacoin
#   currency: yoba
#   min_confirm: 5
#   max_confirm: 6
# - id: 24200
#   key: nibexcoin
#   currency: nbx
#   min_confirm: 5
#   max_confirm: 6
# - id: 24400
#   key: elliotcoin
#   currency: elli
#   min_confirm: 5
#   max_confirm: 6
# - id: 24600
#   key: kingstoncoin
#   currency: kgx
#   min_confirm: 5
#   max_confirm: 6
# - id: 24800
#   key: akencoin
#   currency: akn
#   min_confirm: 5
#   max_confirm: 6
# - id: 25000
#   key: akromacoin
#   currency: aka
#   min_confirm: 5
#   max_confirm: 6
# - id: 25200
#   key: ravencoin
#   currency: rvn
#   min_confirm: 5
#   max_confirm: 6
# - id: 25400
#   key: posqcoin
#   currency: posq
#   min_confirm: 5
#   max_confirm: 6
# - id: 25600
#   key: radiuscoin
#   currency: radius
#   min_confirm: 5
#   max_confirm: 6
# - id: 25800
#   key: discountcoin
#   currency: dsc
#   min_confirm: 5
#   max_confirm: 6
# - id: 26000
#   key: variuscoin
#   currency: varius
#   min_confirm: 5
#   max_confirm: 6
# - id: 26200
#   key: cyphercoin
#   currency: cyr
#   min_confirm: 5
#   max_confirm: 6
# - id: 26400
#   key: blooddonationcoin
#   currency: bbrc
#   min_confirm: 5
#   max_confirm: 6
# - id: 26600
#   key: innoketcoin
#   currency: ikt
#   min_confirm: 5
#   max_confirm: 6
# - id: 26800
#   key: bitsolocoin
#   currency: bsl
#   min_confirm: 5
#   max_confirm: 6
# - id: 27000
#   key: bffcoin
#   currency: bff
#   min_confirm: 5
#   max_confirm: 6
# - id: 27200
#   key: tobacoin
#   currency: toba
#   min_confirm: 5
#   max_confirm: 6
# - id: 27400
#   key: alpenschillingcoin
#   currency: alps
#   min_confirm: 5
#   max_confirm: 6
# - id: 27600
#   key: relariumcoin
#   currency: rlm
#   min_confirm: 5
#   max_confirm: 6
# - id: 27800
#   key: vizehcoin
#   currency: vzh
#   min_confirm: 5
#   max_confirm: 6
# - id: 28000
#   key: rampantcoin
#   currency: rco
#   min_confirm: 5
#   max_confirm: 6
# - id: 28200
#   key: cubiscoin
#   currency: cbc
#   min_confirm: 5
#   max_confirm: 6
# - id: 28400
#   key: examinationcoin
#   currency: exam
#   min_confirm: 5
#   max_confirm: 6
# - id: 28600
#   key: strayacoin
#   currency: nah
#   min_confirm: 5
#   max_confirm: 6
# - id: 28800
#   key: slashcoin
#   currency: slash
#   min_confirm: 5
#   max_confirm: 6
# - id: 29000
#   key: adirondackcoin
#   currency: adr
#   min_confirm: 5
#   max_confirm: 6
# - id: 29200
#   key: hightemperaturecoin
#   currency: htrc
#   min_confirm: 5
#   max_confirm: 6
# - id: 29400
#   key: frozencoin
#   currency: ice
#   min_confirm: 5
#   max_confirm: 6
# - id: 29600
#   key: elbruscoin
#   currency: ebs
#   min_confirm: 5
#   max_confirm: 6
# - id: 29800
#   key: xerumcashcoin
#   currency: xeh
#   min_confirm: 5
#   max_confirm: 6
# - id: 30000
#   key: kickerroomcoin
#   currency: krm
#   min_confirm: 5
#   max_confirm: 6
# - id: 30200
#   key: allcoingurucoin
#   currency: cgur
#   min_confirm: 5
#   max_confirm: 6
# - id: 30400
#   key: versuscoin
#   currency: vre
#   min_confirm: 5
#   max_confirm: 6
# - id: 30600
#   key: heracoin
#   currency: her
#   min_confirm: 5
#   max_confirm: 6
# - id: 30800
#   key: blazariumcoin
#   currency: bzm
#   min_confirm: 5
#   max_confirm: 6
# - id: 31000
#   key: itisnetworkcoin
#   currency: itis
#   min_confirm: 5
#   max_confirm: 6
# - id: 31200
#   key: hppcoin
#   currency: hpp
#   min_confirm: 5
#   max_confirm: 6
# - id: 31400
#   key: designcoin
#   currency: dsn
#   min_confirm: 5
#   max_confirm: 6
# - id: 31600
#   key: demoscoin
#   currency: demos
#   min_confirm: 5
#   max_confirm: 6
# - id: 31800
#   key: jagaricoinr
#   currency: jagar
#   min_confirm: 5
#   max_confirm: 6
