- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  max: 10
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: gravio
  currency: gio
  fixed: 8
  max: 500000
  fee: 0.002
  inuse: true
  type: WithdrawChannelGravio
- id: 600
  key: doge
  currency: doge
  fixed: 8
  max: 500000
  fee: 0.002
  inuse: true
  type: WithdrawChannelDoge
- id: 800
  key: ltc
  currency: ltc
  fixed: 8
  max: 1000
  fee: 0.002
  inuse: true
  type: WithdrawChannelLtc
- id: 1000
  key: ether
  currency: eth
  fixed: 8
  max: 1000
  fee: 0.002
  inuse: true
  type: WithdrawChannelEth

